### ISSUE TITLE
Error in test program

### ISSUE THREAD

**Issue by DovFel** [larshp/abapNTLM#32]
when i use zntlm_test
i can not activtae the program i get error 
methode 'GET' is unknoen or protected or priveate 
in se24 i see the it is publuc 
![Capture1](https://user-images.githubusercontent.com/4284602/129309194-80904341-98bc-4b08-9563-c9eac1869a6f.PNG)
![Capture2](https://user-images.githubusercontent.com/4284602/129309197-9454472f-c10e-46fa-8c23-6ee07228335a.PNG)

**Comment by larshp** [comment]
did you use the latest version of abapGit to install the code?

**Comment by DovFel** [comment]
thanks 
yes i did you use the latest version of abapGit to install the code
but i see its work in ehp7 but not in ehp8 sap ver

**Comment by DovFel** [comment]
head have installed on our upgrade version in it not wortk
i try to to unstall on old version of sap and it is work

**Comment by DovFel** [comment]
> i have installed on our upgrade version in it not wortk
> i try to to install on old version of sap and it is work

I forgot to mention that the previous version works in both systems

**Comment by larshp** [comment]
ok

you can always try copy pasting the class into the system, https://github.com/larshp/abapNTLM/blob/main/src/zcl_ntlm.clas.abap

**Comment by DovFel** [comment]
It is not resolve the problem I did it more the 1 time beafor I open the comment
Thanks

**Comment by DovFel** [comment]
> ok
> 
> you can always try copy pasting the class into the system, https://github.com/larshp/abapNTLM/blob/main/src/zcl_ntlm.clas.abap

I wanted to add you information
I have a function that is used in the department and it continued to work after the new installation
But when I wanted to potentially change code to add the error option and I did activation it fell on error

**Comment by DovFel** [comment]
To make sure the problem is with the upgraded system I performed a tranport from an un upgraded system to the upgraded system and the problem exists

**Comment by DovFel** [comment]
i ddeltet the import version and instal from new and it is work
Thanks

**Comment by DovFel** [comment]
im soory i did some chang in my program and i got the error

**Comment by DovFel** [comment]
i it is work fine it  was my mistake of reasen that not work

**Comment by larshp** [comment]
ok, closing
